{% set version = "0.1.8" %}

package:
  name: pycentroids
  version: {{ version }}

source:
  git_url: https://github.com/NSLS-II/centroids
  git_rev: v{{ version }}

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - setuptools
    - python
    - numpy
    - scipy
    - pytest
    - pytest-runner
    - cmake
    - pandas
    - lmfit-c
    - pybind11
    - gxx_linux-64
    - cpplint

  run:
    - lmfit-c
    - pandas
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
  imports:
    - pycentroids
  commands:
    - pytest --pyargs pycentroids.tests

about:
  home: https://github.com/NSLS-II/centroids
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - stuwilkins
