{% set name = "cpplint" %}
{% set version = "1.4.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/cpplint/cpplint
  git_rev: {{ version }}

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
  run:
    - python

test:
  commands:
    - cpplint --help

about:
  home: https://github.com/cpplint/cpplint
  license: BSD-3-Clause
  license_family: BSD
  summary: Automated checker to ensure C++ files follow Google's style guide

extra:
  recipe-maintainers:
    - stuwilkins
